---
- name: "Updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: "Upgrade all packages"
  apt: upgrade=yes force_apt_get=yes
  become: true
  become_method: sudo
  
- name: "Installing Packages"
  package:
    name:
      - kali-linux-large
      - kali-system-cli
      - kali-system-core
      - kali-tools-exploitation
      - kali-tools-fuzzing
      - kali-tools-passwords
      - kali-tools-post-exploitation
      - kali-tools-windows-resources
      - kali-tools-vulnerability
      - kali-tools-web
      - kali-tools-top10
      - kali-tools-windows-resources
      - bloodhound
      - impacket-scripts
      - ldeep
      - donut
      - certipy-ad
      - netexec
      - autorecon
      - rubeus
      - sharphound
      - bloodyad
      - chisel-common-binaries
      - build-essential
      - bloodhound-ce-python
      - apt-utils
      - cmake 
      - libfontconfig1
      - libkrb5-dev 
      - libglu1-mesa-dev 
      - libgtest-dev 
      - libspdlog-dev 
      - libboost-all-dev 
      - libncurses5-dev 
      - libgdbm-dev 
      - libssl-dev 
      - libreadline-dev 
      - libffi-dev 
      - libsqlite3-dev 
      - libbz2-dev 
      - mesa-common-dev 
      - qtbase5-dev 
      - qtchooser 
      - qt5-qmake 
      - qtbase5-dev-tools 
      - libqt5websockets5 
      - libqt5websockets5-dev 
      - qtdeclarative5-dev 
      - golang-go 
      - qtbase5-dev 
      - libqt5websockets5-dev 
      - python3-pip
      - python3-virtualenv
      - python3-dev 
      - libboost-all-dev 
      - mingw-w64 
      - nasm
      - peass
      - bc
      - openssh-server
      - mingw-w64
      - jq
      - pipx
      - ntpsec-ntpdate
      - flameshot
      - curl
      - dnsrecon
      - enum4linux
      - feroxbuster
      - nbtscan
      - nikto
      - onesixtyone
      - oscanner
      - redis-tools
      - smbclient
      - smbmap
      - snmp
      - sslscan
      - sipvicious
      - tnscmd10g
      - whatweb
      - whois
      - rsyslog
      - ufw
      - rlwrap
      - openssl
      - osslsigncode
      - sshuttle
      - autossh
      - sshpass
      - wget 
      - gpg
      - mage
      - golang-github-binject-go-donut
    state: latest
  become: true
  become_method: sudo

- name: Update APT package cache
  apt:
    update_cache: yes
  become: true
  become_method: sudo

- name: "Download Docker installation script"
  get_url:
    url: https://raw.githubusercontent.com/its-a-feature/Mythic/refs/heads/master/install_docker_kali.sh
    dest: /tmp/install_docker_kali.sh
    mode: '0755'
  become: true
  become_method: sudo

- name: "Install Docker using script"
  shell: /tmp/install_docker_kali.sh
  become: true
  become_method: sudo
  register: docker_install_result

- name: "Clean up Docker installation script"
  file:
    path: /tmp/install_docker_kali.sh
    state: absent
  become: true
  become_method: sudo

- name: "Starting and Enabling Services"
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
     - ssh
     - docker
  become: true
  become_method: sudo

- name: pipx check
  command: pipx ensurepath
  become: true
  become_method: sudo
