---
- name: "Updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: "Upgrade all packages"
  apt: upgrade=yes force_apt_get=yes
  become: true
  become_method: sudo

# All kali tools at https://www.kali.org/tools/all-tools/  
- name: "Installing Packages"
  package:
    name:
      - apt-utils
      - autorecon
      - autossh
      - bc
      - bloodyad
      - build-essential
      - certipy-ad
      - chisel-common-binaries
      - cmake
      - curl
      - dnsrecon
      - donut
      - enum4linux
      - feroxbuster
      - flameshot
      - ghidra
      - golang-github-binject-go-donut
      - golang-go
      - gpg
      - impacket-scripts
      - jq
      - ldeep
      - libbz2-dev
      - libboost-all-dev
      - libboost-all-dev
      - libffi-dev
      - libfontconfig1
      - libgdbm-dev
      - libglu1-mesa-dev
      - libgtest-dev
      - libkrb5-dev
      - libncurses5-dev
      - libqt5websockets5
      - libqt5websockets5-dev
      - libqt5websockets5-dev
      - libreadline-dev
      - libspdlog-dev
      - libsqlite3-dev
      - libssl-dev
      - mage
      - mesa-common-dev
      - mingw-w64
      - mingw-w64
      - mono-devel
      - nasm
      - nbtscan
      - netexec
      - nikto
      - nishang
      - ntpsec-ntpdate
      - onesixtyone
      - openssh-server
      - openssl
      - oscanner
      - osslsigncode
      - peass
      - pipx
      - powercat
      - powershell
      - powersploit
      - python3-dev
      - python3-pip
      - python3-virtualenv
      - qt5-qmake
      - qtbase5-dev
      - qtbase5-dev
      - qtbase5-dev-tools
      - qtchooser
      - qtdeclarative5-dev
      - redis-tools
      - rlwrap
      - rsyslog
      - rubeus
      - sharphound
      - sipvicious
      - smbclient
      - smbmap
      - snmp
      - sshpass
      - sshuttle
      - sslscan
      - tmux
      - tnscmd10g
      - ufw
      - whatweb
      - wget
      - whois
    state: latest
  become: true
  become_method: sudo

# Commment/Uncomment as needed https://www.kali.org/tools/kali-meta/
- name: "Installing Kali Packages"
  package:
    name:
      # - kali-linux-everything
      # - kali-linux-labs
      # - kali-linux-large
      # - kali-system-cli
      # - kali-system-core
      # - kali-tools-802-11
      # - kali-tools-bluetooth
      # - kali-tools-crypto-stego
      # - kali-tools-database
      # - kali-tools-exploitation
      # - kali-tools-forensics
      # - kali-tools-fuzzing
      # - kali-tools-fuzzing
      # - kali-tools-gpu
      # - kali-tools-hardware
      # - kali-tools-information-gathering
      - kali-tools-passwords
      # - kali-tools-post-exploitation
      # - kali-tools-reporting
      # - kali-tools-reverse-engineering
      # - kali-tools-rfid
      # - kali-tools-sdr
      # - kali-tools-sniffing-spoofing
      # - kali-tools-social-engineering
      - kali-tools-top10
      # - kali-tools-voip
      # - kali-tools-vulnerability
      # - kali-tools-web
      - kali-tools-windows-resources
      # - kali-tools-wireless
      # - kali-wallpapers-all
    state: latest
  become: true
  become_method: sudo


- name: Update APT package cache
  apt:
    update_cache: yes
  become: true
  become_method: sudo

- name: "Download Docker installation script"
  get_url:
    url: https://raw.githubusercontent.com/its-a-feature/Mythic/refs/heads/master/install_docker_kali.sh
    dest: /tmp/install_docker_kali.sh
    mode: '0755'
  become: true
  become_method: sudo

- name: "Install Docker using script"
  shell: /tmp/install_docker_kali.sh
  become: true
  become_method: sudo
  register: docker_install_result

- name: "Clean up Docker installation script"
  file:
    path: /tmp/install_docker_kali.sh
    state: absent
  become: true
  become_method: sudo

- name: "Starting and Enabling Services"
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
     - ssh
     - docker
  become: true
  become_method: sudo

- name: pipx check
  command: pipx ensurepath
  become: true
  become_method: sudo
