---
- name: "Updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: "Upgrade all packages"
  apt: upgrade=yes force_apt_get=yes
  become: true
  become_method: sudo
  
- name: "Installing Packages"
  package:
    name:
      - kali-linux-everything
      - build-essential
      - apt-utils
      - cmake 
      - libfontconfig1
      - libkrb5-dev 
      - libglu1-mesa-dev 
      - libgtest-dev 
      - libspdlog-dev 
      - libboost-all-dev 
      - libncurses5-dev 
      - libgdbm-dev 
      - libssl-dev 
      - libreadline-dev 
      - libffi-dev 
      - libsqlite3-dev 
      - libbz2-dev 
      - mesa-common-dev 
      - qtbase5-dev 
      - qtchooser 
      - qt5-qmake 
      - qtbase5-dev-tools 
      - libqt5websockets5 
      - libqt5websockets5-dev 
      - qtdeclarative5-dev 
      - golang-go 
      - qtbase5-dev 
      - libqt5websockets5-dev 
      - python3-dev 
      - libboost-all-dev 
      - mingw-w64 
      - nasm
      - kali-tools-crypto-stego
      - kali-tools-fuzzing
      - kali-tools-windows-resources
      - kali-linux-large
      - kali-wallpapers-all
      - peass
      - bc
      - xplico
      - openssh-server
      - mingw-w64
      - jq
      - pipx
      - ntpdate
      - flameshot
      - exiftool
      - evilginx2
      - evilginx2-dbgsym
      - pure-ftpd
      - curl
      - dnsrecon
      - enum4linux
      - feroxbuster
      - nbtscan
      - nikto
      - onesixtyone
      - oscanner
      - redis-tools
      - smbclient
      - smbmap
      - snmp
      - sslscan
      - sipvicious
      - tnscmd10g
      - whatweb
      - wkhtmltopdf
      - podman
      - apache2
      - postfix
      - nginx
      - nginx-extras
      - whois
      - rsyslog
      - ufw
      - rlwrap
      - openssl
      - osslsigncode
      - sshuttle
      - docker-compose
    state: latest
  become: true
  become_method: sudo

- name: "Installing python packages"
  ansible.builtin.pip:
    name: 
      - mechanicalsoup
      - openpyxl
      - Faker
      - python-docx
      - python-pptx
      - requests
      - fabric
      - wmi
      - requests-html
      - numpy
      - selenium
      - webdriver-manager
      - tldextract
      - bs4
      - pycryptodome
      - minikerberos

# - name: Remove Docker
#   ansible.builtin.file:
#     path: /usr/bin/docker
#     state: absent
#   become: true
#   become_method: sudo
  
# - name: Adding Docker GPG key
#   apt_key:
#     url: https://download.docker.com/linux/debian/gpg
#     state: present
#   become: true
#   become_method: sudo

# - name: Add Docker repository
#   apt_repository:
#     repo: deb [arch=amd64] https://download.docker.com/linux/debian bookworm stable
#     state: present
#   become: true
#   become_method: sudo

- name: "Setting up Veil" 
  ansible.builtin.shell:
    cmd: "/usr/share/veil/config/setup.sh --force --silent"
  become: true
  become_method: sudo

- name: Update APT package cache
  apt:
    update_cache: yes
  become: true
  become_method: sudo

# - name: "Install Docker"
#   apt:
#     name: 
#        - docker-ce
#        - docker-compose-plugin
#     state: present
#     install_recommends: false
#   become: true
#   become_method: sudo


- name: "Starting and Enabling Services"
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
     - ssh
     - rsyslog
     - ufw
     - docker
  become: true
  become_method: sudo

- name: pipx check
  command: pipx ensurepath
  become: true
  become_method: sudo
