---
- name: "Updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: "Upgrade all packages"
  apt: upgrade=yes force_apt_get=yes
  become: true
  become_method: sudo

- name: "Installing Kali Packages"
  package:
    name: "{{ apt_meta_packages }}"
    state: latest
  become: true
  become_method: sudo

- name: "Installing Packages"
  package:
    name: "{{ apt_packages }}"
    state: latest
  become: true
  become_method: sudo

- name: Update APT package cache
  apt:
    update_cache: yes
  become: true
  become_method: sudo

- name: "Download Docker installation script"
  get_url:
    url: https://raw.githubusercontent.com/its-a-feature/Mythic/refs/heads/master/install_docker_kali.sh
    dest: /tmp/install_docker_kali.sh
    mode: '0755'
  become: true
  become_method: sudo

- name: "Install Docker using script"
  shell: /tmp/install_docker_kali.sh
  become: true
  become_method: sudo
  register: docker_install_result

- name: "Clean up Docker installation script"
  file:
    path: /tmp/install_docker_kali.sh
    state: absent
  become: true
  become_method: sudo

- name: "Starting and Enabling Services"
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
     - ssh
     - docker
  become: true
  become_method: sudo

- name: pipx check
  command: pipx ensurepath
  become: true
  become_method: sudo
