---
  - name: Creating buildprep file
    copy:
      dest: /tmp/buildprep
      content: |
        {{ ansible_user_id }}    ALL=(ALL) NOPASSWD: ALL

  - name: perm check
    command: chown root:root /tmp/buildprep 
    become: true
    become_method: sudo

  - name: Updating sudoers.d
    command: mv /tmp/buildprep /etc/sudoers.d/
    become: true
    become_method: sudo

  - name: Fixing permissions
    file:
      path: /etc/sudoers.d/buildprep
      owner: root
      group: root
      mode: '0440'
    become: true
    become_method: sudo

