---
  - name: Configure passwordless sudo
    copy:
      dest: /etc/sudoers.d/buildprep
      content: "{{ ansible_facts['user_id'] }}    ALL=(ALL) NOPASSWD: ALL\n"
      owner: root
      group: root
      mode: '0440'
    become: true
    become_method: sudo
