---
  - name: Configure passwordless sudo
    copy:
      dest: /etc/sudoers.d/buildprep
      content: "{{ ansible_facts['user_id'] }}    ALL=(ALL) NOPASSWD: ALL\n"
      owner: root
      group: root
      mode: '0440'
    become: true
    become_method: sudo

  - name: Ensure .ssh directory exists
    file:
      path: "{{ ansible_env.HOME }}/.ssh"
      state: directory
      owner: "{{ ansible_facts['user_id'] }}"
      mode: '0700'

  - name: Generate ed25519 SSH key pair
    community.crypto.openssh_keypair:
      path: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
      type: ed25519
      comment: "{{ ansible_facts['user_id'] }}@{{ ansible_facts['hostname'] }}"
      owner: "{{ ansible_facts['user_id'] }}"

  - name: Create .ssh/config file
    copy:
      dest: "{{ ansible_env.HOME }}/.ssh/config"
      content: ""
      owner: "{{ ansible_facts['user_id'] }}"
      mode: '0600'
      force: false