---
  - name: Configure passwordless sudo
    copy:
      dest: /etc/sudoers.d/buildprep
      content: "{{ ansible_facts['user_id'] }}    ALL=(ALL) NOPASSWD: ALL\n"
      owner: root
      group: root
      mode: '0440'
    become: true
    become_method: sudo

  - name: "Configure /etc/network/interfaces"
    ansible.builtin.copy:
      dest: /etc/network/interfaces
      owner: root
      group: root
      mode: '0644'
      content: |
        auto lo
        iface lo inet loopback

        auto eth0
        iface eth0 inet dhcp

        auto eth1
        iface eth1 inet static
            address 192.168.57.40
            netmask 255.255.255.0
    become: true
    become_method: sudo
    when: "'eth1' in ansible_facts['interfaces']"

  - name: "Restart networking"
    ansible.builtin.service:
      name: networking
      state: restarted
    become: true
    become_method: sudo
    when: "'eth1' in ansible_facts['interfaces']"