---
# - name: Add Microsoft GPG key
#   apt_key:
#     url: https://packages.microsoft.com/keys/microsoft.asc
#     state: present
#   become: true
#   become_method: sudo

# - name: Add VSCode repository
#   apt_repository:
#     repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
#     state: present
#   become: true
#   become_method: sudo

# - name: Update APT package cache
#   apt:
#     update_cache: yes
#   become: true
#   become_method: sudo

# - name: "Install Visual Studio Code"
#   apt:
#     name: code
#     state: present

# Download Microsoft GPG key
- name: Download Microsoft GPG key
  ansible.builtin.command: "wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg && sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg"
  become: true
  become_method: sudo  

# Add VS Code repository
- name: Add VS Code repository
  ansible.builtin.shell: echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" | tee /etc/apt/sources.list.d/vscode.list > /dev/null
  args:
    creates: /etc/apt/sources.list.d/vscode.list
  become: true
  become_method: sudo

# Remove temporary GPG file
- name: Remove temporary GPG file
  ansible.builtin.file:
    path: packages.microsoft.gpg
    state: absent
  become: true
  become_method: sudo    
 
# Install apt-transport-https
- name: Install apt-transport-https
  ansible.builtin.apt:
    name: apt-transport-https
    state: present
  become: true
  become_method: sudo

# Update apt cache
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: true
  become_method: sudo

# Install VS Code
- name: Install VS Code
  ansible.builtin.apt:
    name: code
    state: present
  become: true
  become_method: sudo

- name: "Getting VSCode extensions"
  ansible.builtin.command:
    cmd: "code --install-extension {{ item }}"    
  loop:
    - ms-python.python
    - ms-python.vscode-pylance
    - kosz78.nim
    - streetsidesoftware.code-spell-checker
    - ms-vscode.cpptools
    - DEVSENSE.phptools-vscode
    - ms-dotnettools.csharp
    - ms-azuretools.vscode-docker


# - name: Getting VSCode extenssions
#   ansible.builtin.command:
#     cmd: code --install-extension kosz78.nim

# - name: Getting VSCode extenssions
#   ansible.builtin.command:
#     cmd: code --install-extension streetsidesoftware.code-spell-checker

# - name: Getting VSCode extenssions
#   ansible.builtin.command:
#     cmd: code --install-extension ms-vscode.cpptools

# - name: Getting VSCode extenssions
#   ansible.builtin.command:
#     cmd: code --install-extension DEVSENSE.phptools-vscode

# - name: Getting VSCode extenssions
#   ansible.builtin.command:
#     cmd: code --install-extension ms-dotnettools.csharp

# - name: Getting VSCode extenssions
#   ansible.builtin.command:
#     cmd: code --install-extension ms-azuretools.vscode-docker

# - name: Getting VSCode extenssions
#   ansible.builtin.command:
#     cmd: code --install-extension ms-python.vscode-pylance
