---
- name: Check if dos2unix is installed
  command: which dos2unix
  register: dos2unix_check
  ignore_errors: true
  changed_when: false
  become: true
  become_method: sudo

- name: Install dos2unix if not present
  package:
    name: dos2unix
    state: present
  when: dos2unix_check.rc != 0
  become: true
  become_method: sudo  
  
- name: Copy the VSCode installation script
  copy:
    src: "{{ role_path }}/files/code/install_vscode.sh"  # Update with the local path to your script
    dest: /tmp/install_vscode.sh
    mode: '0755'  # Make the script executable
  become: true
  become_method: sudo    
  
- name: Run dos2unix on the script
  command: dos2unix /tmp/install_vscode.sh
  become: true
  become_method: sudo  
  
- name: Execute the VSCode installation script
  command: /tmp/install_vscode.sh
  become: true
  become_method: sudo  
  
- name: Delete the script after execution
  file:
    path: /tmp/install_vscode.sh
    state: absent
  become: true
  become_method: sudo

- name: "Getting VSCode extensions"
  ansible.builtin.command:
    cmd: "code --install-extension {{ item }}"    
  loop:
    - ms-python.python
    - ms-python.vscode-pylance
    - kosz78.nim
    - streetsidesoftware.code-spell-checker
    - ms-vscode.cpptools
    - DEVSENSE.phptools-vscode
    - ms-dotnettools.csharp
    - ms-azuretools.vscode-docker
  ignore_errors: true  


# - name: Getting VSCode extenssions
#   ansible.builtin.command:
#     cmd: code --install-extension kosz78.nim

# - name: Getting VSCode extenssions
#   ansible.builtin.command:
#     cmd: code --install-extension streetsidesoftware.code-spell-checker

# - name: Getting VSCode extenssions
#   ansible.builtin.command:
#     cmd: code --install-extension ms-vscode.cpptools

# - name: Getting VSCode extenssions
#   ansible.builtin.command:
#     cmd: code --install-extension DEVSENSE.phptools-vscode

# - name: Getting VSCode extenssions
#   ansible.builtin.command:
#     cmd: code --install-extension ms-dotnettools.csharp

# - name: Getting VSCode extenssions
#   ansible.builtin.command:
#     cmd: code --install-extension ms-azuretools.vscode-docker

# - name: Getting VSCode extenssions
#   ansible.builtin.command:
#     cmd: code --install-extension ms-python.vscode-pylance
