---
- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
  register: build_dir

- name: "Installing useful github repos"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.location }}"
    version: "{{ item.version | default(omit) }}"
    depth: "{{ item.depth | default(1) }}"
    single_branch: true
    force: true
  loop: "{{ github_repos }}"
  become: true
  become_method: sudo

- name: "Copying python script to download github releases"
  copy:
    src: "files/githubdownload.py"
    dest: "{{ build_dir.path }}/githubdownload.py"
    owner: root
    group: root
    mode: 0755
  become: true
  become_method: sudo

- name: "Downloading github releases"
  shell: "{{ build_dir.path }}/githubdownload.py {{ item.repo }} {{ item.regex }} {{ item.location }} {% if item.filename is defined %}{{ item.filename }}{% endif %}"
  loop: "{{ github_releases }}"
  async: 45
  poll: 0
  become: true
  become_method: sudo

- name: Remove temporary build directory
  ansible.builtin.file:
    path: "{{ build_dir.path }}"
    state: absent
  when: build_dir.path is defined

- name: "Recursively change ownership and permissions of /opt/"
  ansible.builtin.file:
    path: /opt
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    recurse: true
  become: true
  become_method: sudo
