---
- name: "go install Kerbrute"
  ansible.builtin.shell:
    cmd: go install github.com/ropnop/kerbrute@latest
  ignore_errors: true  

- name: "go install garble"
  ansible.builtin.shell:
    cmd: go install mvdan.cc/garble@latest
  ignore_errors: true  

- name: "go install GoBuster"
  ansible.builtin.shell:
    cmd: go install github.com/OJ/gobuster/v3@latest
  ignore_errors: true  

- name: "go install GoWitness"
  ansible.builtin.shell:
    cmd: go install github.com/sensepost/gowitness@latest
  ignore_errors: true  

- name: "go install LDAPNomNom"
  ansible.builtin.shell:
    cmd: go install github.com/lkarlslund/ldapnomnom@latest
  ignore_errors: true