---
- name: "go install Kerbrute"
  ansible.builtin.shell:
    cmd: go install github.com/ropnop/kerbrute@latest

- name: "go install garble"
  ansible.builtin.shell:
    cmd: go install mvdan.cc/garble@latest

- name: "go install color"
  ansible.builtin.shell:
    cmd: go install github.com/fatih/color@latest

- name: "go install zip"
  ansible.builtin.shell:
    cmd: go install github.com/yeka/zip@latest

- name: "go install version_info"
  ansible.builtin.shell:
    cmd: go install github.com/josephspurrier/goversioninfo@latest

- name: "go install pe debug"
  ansible.builtin.shell:
    cmd: go install github.com/Binject/debug/pe@latest

- name: "go install rawreader"
  ansible.builtin.shell:
    cmd: go install github.com/awgh/rawreader@latest  
