---
- name: "Creating Nim modules directory"
  ansible.builtin.file:
    path: "/opt/nimmods"
    state: directory
    mode: '0755'

- name: "Installing useful github repos"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.location }}"
    depth: "{{ item.depth | default(1) }}"
    single_branch: true
    force: true
  loop: "{{ nim_repos }}"
