---
- name: "Install pipx tools"
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.url }}"
    state: install
    system_site_packages: true
  loop:
    - { name: 'adidnsdump', url: 'git+https://github.com/dirkjanm/adidnsdump.git' }
    - { name: 'wesng', url: 'git+https://github.com/bitsadmin/wesng.git' }  
    - { name: 'bloodyAD', url: 'git+https://github.com/CravateRouge/bloodyAD.git'}
  ignore_errors: true