---
- name: "Install pipx tools from Github"
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.url }}"
    state: install
    system_site_packages: true
  loop: "{{ pipx_git_tools }}"
  ignore_errors: true

- name: "Install pipx tools from package"
  community.general.pipx:
    name: "{{ item }}"
    state: latest
    system_site_packages: true
  loop: "{{ pipx_packages }}"
  ignore_errors: true
