---
- name: "Creating Redirector directory"
  ansible.builtin.file:
    path: "/opt/redirector"
    state: directory
    mode: '0755'
  become: true
  become_method: sudo

- name: "Adding files to new directory"
  copy:
    src: "{{ item }}"
    dest: "/opt/redirector/"
  with_fileglob:
    - "{{ role_path }}/files/*"
  become: true
  become_method: sudo    

- name: "Adding ca directory"
  copy:
    src: "{{ role_path }}/files/ca"
    dest: "/opt/redirector/ca/"
    remote_src: true
  become: true
  become_method: sudo  
    
- name: "Adding phish directory"
  copy:
    src: "{{ role_path }}/files/phish"
    dest: "/opt/redirector/phish/"
    remote_src: true 
  become: true
  become_method: sudo

- name: Install Apache and nginx
  package:
    name:
      - apache2
      - nginx
    state: present
  become: true
  become_method: sudo

- name: "Enabling Apache Mods"
  ansible.builtin.command:
    cmd: /usr/sbin/a2enmod {{ item }}
    creates: /etc/apache2/mods-enabled/{{ item }}.load
  loop:
    - proxy
    - proxy_http
    - rewrite
    - headers
    - ssl
    - cache
  become: true
  become_method: sudo

- name: Stop and disable Apache and nginx
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - apache2
    - nginx
  become: true
  become_method: sudo

