---
- name: "Creating SysInternals directory"
  ansible.builtin.file:
    path: "/opt/sysinternals"
    state: directory
    mode: '0755'

- name: Download SysInternals
  ansible.builtin.get_url:
    url: https://download.sysinternals.com/files/SysinternalsSuite.zip
    dest: /opt/sysinternals/SysinternalsSuite.zip
    mode: '0755'

- name: "Recursively change ownership and permissions of /opt/"
  ansible.builtin.command:
    cmd: "chown -R {{ ansible_user_id }}:{{ ansible_user_id }} /opt/" 
  become: true
  become_method: sudo    