- name: "Installing mount-shared-foldersn"
  ansible.builtin.copy:
    src: /usr/lib/kali_tweaks/data/mount-shared-folders
    dest: /usr/local/sbin/mount-shared-folders
    remote_src: true
    mode: "0755"
  become: true
  become_method: sudo

- name: "Installing restart-vm-tools"
  ansible.builtin.copy:
    src: /usr/lib/kali_tweaks/data/restart-vm-tools
    dest: /usr/local/sbin/restart-vm-tools
    remote_src: true
    mode: "0755"
  become: true
  become_method: sudo
