---
- name: "Auto removing packages"
  apt: 
    autoremove: yes
  become: true
  become_method: sudo

- name: "Running clean"
  apt: 
    clean: yes
  become: true
  become_method: sudo
  
- name: "Deleting buildprep in sudoers.d"
  file:
    path: /etc/sudoers.d/buildprep
    state: absent
  become: true
  become_method: sudo
