---
# These should already be installed but extra confirmation 
- name: "Install Extension-Kit Dependencies"
  package:
    name:
      - g++-mingw-w64-x86-64-posix
      - gcc-mingw-w64-x86-64-posix
      - mingw-w64-tools
      - default-jre 
      - gcc-mingw-w64-x86-64 
      - clang 
      - lld 
      - make
      - docker-buildx-plugin
    state: latest
  become: true
  become_method: sudo

- name: "Build Extension-Kit"
  ansible.builtin.shell:
    cmd: make all
    chdir: /opt/extension-kit
  become: true
  become_method: sudo

- name: "Making setup script for Adaptix executable"
  ansible.builtin.shell:
    cmd: chmod +x ./pre_install_linux_all.sh
    chdir: /opt/AdaptixC2
  become: true
  become_method: sudo 

- name: "Executing setup script for Adaptix Server"
  ansible.builtin.shell:
    cmd: ./pre_install_linux_all.sh server
    chdir: /opt/AdaptixC2
  become: true
  become_method: sudo 

- name: "Executing setup script for Adaptix Client"
  ansible.builtin.shell:
    cmd: ./pre_install_linux_all.sh client
    chdir: /opt/AdaptixC2
  become: true
  become_method: sudo 

- name: "Copy AdaptixClient to Desktop"
  ansible.builtin.copy:
    src: /opt/AdaptixC2/dist/AdaptixClient
    dest: "/home/{{ ansible_facts['user_id'] }}/Desktop/"
    remote_src: yes

- name: "Make AdaptixClient executable"
  ansible.builtin.file:
    path: "/home/{{ ansible_facts['user_id'] }}/Desktop/AdaptixClient"
    mode: '0755'

- name: "Build Reflectra for Adaptix"
  ansible.builtin.shell:
    cmd: |
      chmod +x install.sh
      ./install.sh
    chdir: /opt/reflectra
  become: true
  become_method: sudo

# Look into building workflow??
# https://github.com/k1ng0fn0th1ng/CrystalForge.git
# 
- name: "Clone CrystalForge into Adaptix extenders"
  ansible.builtin.git:
    repo: "https://github.com/k1ng0fn0th1ng/CrystalForge.git"
    dest: /opt/AdaptixC2/AdaptixServer/extenders/CrystalForge
    force: true
  become: true
  become_method: sudo

- name: "Add CrystalForge to Adaptix"
  ansible.builtin.shell:
    cmd: |
      go work use extenders/CrystalForge
      go work sync
    chdir: /opt/AdaptixC2/AdaptixServer
  become: true
  become_method: sudo

- name: "Build AdaptixC2"
  ansible.builtin.shell:
    cmd: make all
    chdir: /opt/AdaptixC2
  become: true
  become_method: sudo   

- name: "Build Kharon for Adaptix"
  ansible.builtin.shell:
    cmd: |
      chmod +x setup_kharon.sh
      ./setup_kharon.sh --ax /opt/AdaptixC2/ --action all
    chdir: /opt/Kharon
  become: true
  become_method: sudo

- name: "Update Adaptix profile.yaml" 
  ansible.builtin.shell:
    cmd: |
      sed -i 's|    - "extenders/gopher_agent/config.yaml"|    - "extenders/gopher_agent/config.yaml"\n    - "extenders/agent_kharon/config.yaml"\n    - "extenders/listener_kharon_http/config.yaml"\n    - "extenders/CrystalForge/config.yaml|' profile.yaml
    chdir: /opt/AdaptixC2/dist/
  become: true
  become_method: sudo   

- name: "Create Adaptix Certificates"
  ansible.builtin.shell:
    cmd: >
      openssl req -x509 -nodes -newkey rsa:2048
      -keyout server.rsa.key
      -out server.rsa.crt
      -days 365
      -subj "/C=US/ST=State/L=City/O=Organization/OU=Unit/CN=localhost"
    chdir: /opt/AdaptixC2/dist/
  become: true
  become_method: sudo
