---
# These should already be installed but extra confirmation 
- name: "Install Extension-Kit Dependencies"
  package:
    name:
      - g++-mingw-w64-x86-64-posix
      - gcc-mingw-w64-x86-64-posix
      - mingw-w64-tools
      - default-jre 
      - gcc-mingw-w64-x86-64 
      - clang 
      - lld 
      - make
      - docker-buildx-plugin
    state: latest
  become: true
  become_method: sudo

- name: "Build Extension-Kit"
  ansible.builtin.shell:
    cmd: make docker-build-client
    chdir: /opt/extension-kit
  become: true
  become_method: sudo

- name: "Making setup script for Adaptix executable"
  ansible.builtin.shell:
    cmd: chmod +x pre_install_linux_all.sh
    chdir: /opt/AdaptixC2
  become: true
  become_method: sudo 

- name: "Executing setup script for Adaptix Server"
  ansible.builtin.shell:
    cmd: pre_install_linux_all.sh server
    chdir: /opt/AdaptixC2
  become: true
  become_method: sudo 

- name: "Executing setup script for Adaptix Client"
  ansible.builtin.shell:
    cmd: pre_install_linux_all.sh client
    chdir: /opt/AdaptixC2
  become: true
  become_method: sudo 

- name: "Build AdaptixC2 -- THIS TAKES A MIN GO GET COFFEE!!!!!"
  ansible.builtin.shell:
    cmd: make server-ext
    chdir: /opt/AdaptixC2
  become: true
  become_method: sudo 

- name: "Create Adaptix Certificates"
  ansible.builtin.shell:
    cmd: >
      openssl req -x509 -nodes -newkey rsa:2048
      -keyout server.rsa.key
      -out server.rsa.crt
      -days 365
      -subj "/C=US/ST=State/L=City/O=Organization/OU=Unit/CN=localhost"
    chdir: /opt/AdaptixC2/AdaptixServer/server-dist
  become: true
  become_method: sudo

- name: "Build Stealth Palace for Adaptix"
  ansible.builtin.shell:
    cmd: |
      chmod +x install.sh
      ./install.sh --ax /opt/AdaptixC2/dist/
    chdir: /opt/adaptix_stealthpalace
  become: true
  become_method: sudo

- name: "Clone original AdaptixC2 to home directory"
  ansible.builtin.git:
    repo: "https://github.com/Adaptix-Framework/AdaptixC2.git"
    dest: "{{ /home/{{ ansible_facts['user_id'] }} }}/OGAdaptix"
    force: true

- name: "Build original AdaptixC2 client"
  ansible.builtin.shell:
    cmd: make client
    chdir: "{{ /home/{{ ansible_facts['user_id'] }} }}/OGAdaptix"

- name: "Copy AdaptixClient to Desktop"
  ansible.builtin.copy:
    src: "{{ /home/{{ ansible_facts['user_id'] }} }}/OGAdaptix/dist/AdaptixClient"
    dest: "{{ /home/{{ ansible_facts['user_id'] }} }}/Desktop/"
    remote_src: yes

# - name: "Creating symlinks"
#   ansible.builtin.file:
#     src: "{{ item.src }}"
#     path: "{{ item.dst }}"
#     state: link
#   loop:
#     - { src: /opt/AdaptixC2/AdaptixServer/server-dist/adaptixserver, dst: /usr/bin/adaptixserver }
#     - { src: /opt/AdaptixC2/AdaptixClient/client-dist/AdaptixClient-x86_64.AppImage, dst: /usr/bin/adaptixclient }
#   become: true
#   become_method: sudo
#   ignore_errors: true 
