---
- name: Create a BloodhoundCE directory 
  ansible.builtin.file:
    path: /opt/bloodhound
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: 0755

- name: "Copying BloodhoundCE config"
  copy:
    src: "files/bloodhound.config.json"
    dest: /opt/bloodhound/bloodhound.config.json
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    mode: 0755  

- name: "Copy Compose File" 
  ansible.builtin.copy:
    src: /opt/bloodhound/examples/docker-compose/docker-compose.yml 
    dest: /opt/bloodhound/docker-compose.yml 
  become: true
  become_method: sudo   

- name: "Build Bloodhound-CE"
  ansible.builtin.shell:
    cmd: "docker compose up -d"
    chdir: /opt/bloodhound/
  become: true
  become_method: sudo

- name: "Down Bloodhound-CE"
  ansible.builtin.shell:
    cmd: "docker compose down -v"
    chdir: /opt/bloodhound
  become: true
  become_method: sudo  
# to get password run docker-compose down -v and then docker-compose up --force-recreate    