---
# - name: "Creating a windapsearch symlink"
#   ansible.builtin.shell:
#     cmd: ln -s /opt/windapsearch/windapsearch.py /usr/bin/windapsearch
#   become_method: sudo  

# - name: "Creating a hoaxshell symlink"
#   ansible.builtin.shell:
#     cmd: ln -s /opt/hoaxshell/hoaxshell.py /usr/bin/hoaxshell
#   become_method: sudo  

# - name: "Creating a adidnsdump symlink"
#   ansible.builtin.shell:
#     cmd: ln -s "{{ ansible_facts['env']['HOME'] }}/.local/pipx/venvs/adidnsdump/bin/adidnsdump" /usr/bin/adidnsdump
#   become_method: sudo  

- name: "Creating symlinks"
  ansible.builtin.file:
    src: "{{ item.src }}"
    path: "{{ item.dst }}"
    state: link
  loop:
    - { src: /opt/windapsearch/windapsearch.py, dst: /usr/bin/windapsearch }
    - { src: "{{ ansible_facts['env']['HOME'] }}/.local/share/pipx/venvs/adidnsdump/bin/adidnsdump", dst: /usr/bin/adidnsdump }
    - { src: "{{ ansible_facts['env']['HOME'] }}/.local/share/pipx/venvs/bloodyad/bin/bloodyAD", dst: /usr/bin/bloodyAD }
    - { src: /opt/wesng/wes.py, dst: /usr/bin/wesng }
    - { src: /opt/wesng/wes.py, dst: /usr/bin/wes }  
    - { src: "{{ ansible_facts['env']['HOME'] }}/.nimble/bin/choosenim", dst: /usr/bin/choosenim }
    - { src: "{{ ansible_facts['env']['HOME'] }}/.nimble/bin/nim", dst: /usr/bin/nim }
    - { src: "{{ ansible_facts['env']['HOME'] }}/.nimble/bin/nim-gdb", dst: /usr/bin/nim-gdb }  
    - { src: "{{ ansible_facts['env']['HOME'] }}/.nimble/bin/nimble", dst: /usr/bin/nimble }  
    - { src: "{{ ansible_facts['env']['HOME'] }}/.nimble/bin/nimgrep", dst: /usr/bin/nimgrep }  
    - { src: "{{ ansible_facts['env']['HOME'] }}/.nimble/bin/nimpretty", dst: /usr/bin/nimpretty }  
    - { src: "{{ ansible_facts['env']['HOME'] }}/.nimble/bin/nimsuggest", dst: /usr/bin/nimsuggest }  
    - { src: "{{ ansible_facts['env']['HOME'] }}/.nimble/bin/testament", dst: /usr/bin/testament }
    - { src: "{{ ansible_facts['env']['HOME'] }}/.cargo/bin/cargo", dst: /usr/bin/cargo }  
    - { src: "{{ ansible_facts['env']['HOME'] }}/.cargo/bin/cargo-clippy", dst: /usr/bin/cargo-clippy }
    - { src: "{{ ansible_facts['env']['HOME'] }}/.cargo/bin/cargo-fmt", dst: /usr/bin/cargo-fmt }     
    - { src: "{{ ansible_facts['env']['HOME'] }}/.cargo/bin/cargo-miri", dst: /usr/bin/cargo-miri }     
    - { src: "{{ ansible_facts['env']['HOME'] }}/.cargo/bin/clippy-driver", dst: /usr/bin/clippy-driver }     
    - { src: "{{ ansible_facts['env']['HOME'] }}/.cargo/bin/rls", dst: /usr/bin/rls }     
    - { src: "{{ ansible_facts['env']['HOME'] }}/.cargo/bin/rust-analyzer", dst: /usr/bin/rust-analyzer }     
    - { src: "{{ ansible_facts['env']['HOME'] }}/.cargo/bin/rust-gdb", dst: /usr/bin/rust-gdb }     
    - { src: "{{ ansible_facts['env']['HOME'] }}/.cargo/bin/rust-gdbgui", dst: /usr/bin/rust-gdbgui }     
    - { src: "{{ ansible_facts['env']['HOME'] }}/.cargo/bin/rust-lldb", dst: /usr/bin/rust-lldb }     
    - { src: "{{ ansible_facts['env']['HOME'] }}/.cargo/bin/rustc", dst: /usr/bin/rustc }     
    - { src: "{{ ansible_facts['env']['HOME'] }}/.cargo/bin/rustdoc", dst: /usr/bin/rustdoc }     
    - { src: "{{ ansible_facts['env']['HOME'] }}/.cargo/bin/rustfmt", dst: /usr/bin/rustfmt }     
    - { src: "{{ ansible_facts['env']['HOME'] }}/.cargo/bin/rustup", dst: /usr/bin/rustup }
    - { src: "{{ ansible_facts['env']['HOME'] }}/.cargo/bin/rustup", dst: /usr/bin/rustup }
    - { src: "{{ ansible_facts['env']['HOME'] }}/go/bin/garble", dst: /usr/bin/garble }
    - { src: "{{ ansible_facts['env']['HOME'] }}/go/bin/kerbrute", dst: /usr/bin/kerbrute }
    - { src: /root/.dotnet/dotnet, dst: /usr/bin/dotnet }
    - { src: /opt/FaceDancer/FaceDancer, dst: /usr/bin/FaceDancer }
    - { src: /opt/limelighter/Limelighter, dst: /usr/bin/Limelighter } 
  become: true
  become_method: sudo
  ignore_errors: true 

  
- name: "Recursively change ownership and permissions of /opt/"
  ansible.builtin.command:
    cmd: "chown -R {{ ansible_facts['user_id'] }}:{{ ansible_facts['user_id'] }} /opt/" 
  become: true
  become_method: sudo
  
  
  
  
  
  
  
  
  
