---
- name: "Creating required symlinks"
  ansible.builtin.file:
    src: "{{ item.src }}"
    path: "{{ item.dst }}"
    state: link
    force: true
  loop: "{{ finallinks_required }}"
  become: true
  become_method: sudo

- name: "Creating optional symlinks"
  ansible.builtin.file:
    src: "{{ item.src }}"
    path: "{{ item.dst }}"
    state: link
    force: true
  loop: "{{ finallinks_optional }}"
  become: true
  become_method: sudo
  ignore_errors: true

- name: "Recursively change ownership and permissions of /opt/"
  ansible.builtin.file:
    path: /opt
    state: directory
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_id'] }}"
    recurse: true
  become: true
  become_method: sudo
