---
- name: "Verify docker is running"
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  become: true
  become_method: sudo

- name: "Installing Ghostwriter cli"
  ansible.builtin.shell:
    cmd: "/opt/ghostwriter/ghostwriter-cli-linux install"
  become: true
  become_method: sudo

- name: "Fixing Docker Restart configs"
  ansible.builtin.replace:
    path: "{{ item }}"
    regexp: "restart: always"
    replace: "restart: on-failure:10"
  loop:
    - /opt/ghostwriter/production.yml
    - /opt/ghostwriter/local.yml
  become: true
  become_method: sudo
  ignore_errors: true

- name: "Fixing Ghostwriter Ports"
  ansible.builtin.replace:
    path: /opt/ghostwriter/production.yml
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - { regexp: "0.0.0.0:80:80", replace: "0.0.0.0:8980:80" }
    - { regexp: "0.0.0.0:443:443", replace: "0.0.0.0:8443:443" }
  become: true
  become_method: sudo
  ignore_errors: true

- name: "Rebuilding Ghostwriter" 
  ansible.builtin.shell:
    cmd: "/opt/ghostwriter/ghostwriter-cli-linux containers down"
  become: true
  become_method: sudo

- name: "Rebuilding Ghostwriter" 
  ansible.builtin.shell:
    cmd: "/opt/ghostwriter/ghostwriter-cli-linux containers up"
  become: true
  become_method: sudo

- name: "Fixing Ghostwriter Restart" 
  ansible.builtin.shell:
    cmd: "docker update --restart on-failure:10 $(docker ps -q)"
  become: true
  become_method: sudo

- name: "Rebuilding Ghostwriter" 
  ansible.builtin.shell:
    cmd: "/opt/ghostwriter/ghostwriter-cli-linux containers stop"
  become: true
  become_method: sudo
 
- name: "Creating a symlink"
  ansible.builtin.file:
    src: /opt/ghostwriter/ghostwriter-cli-linux
    dest: /usr/bin/ghostwriter-cli
    state: link
  become: true
  become_method: sudo 