---
# - name: "go install mod sys"
#   ansible.builtin.shell:
#     cmd: go mod download golang.org/x/sys
#     chdir: /opt/havoc/teamserver

# - name: "go install mod ugorji/go"
#   ansible.builtin.shell:
#     cmd: go mod download github.com/ugorji/go
#     chdir: /opt/havoc/teamserver

# - name: "Build havoc team server"
#   ansible.builtin.shell:
#     cmd: make ts-build
#     chdir: /opt/havoc/
#   become: true
#   become_method: sudo  

# - name: "Build havoc client"
#   ansible.builtin.shell:
#     cmd: make client-build
#     chdir: /opt/havoc/

- name: "Installing Havoc Modules"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.location }}"
    force: true
  loop:
    - { repo: "https://github.com/icyguider/LatLoader.git", location: "/usr/share/havoc/client/Modules/LatLoader" }  
    - { repo: "https://github.com/jakobfriedl/havoc-NoPowerShell", location: "/usr/share/havoc/client/Modules/NoPowerShell" }
    - { repo: "https://github.com/jakobfriedl/mitre4havoc.git", location: "/usr/share/havoc/client/Modules/mitre4havoc" } 
    - { repo: "https://github.com/jakobfriedl/havoc-reporter.git", location: "/usr/share/havoc/client/Modules/Reporter" }  
  become: true
  become_method: sudo

- name: "Build LatLoader Module"
  ansible.builtin.shell:
    cmd: make 
    chdir: /usr/share/havoc/client/Modules/LatLoader
  become: true
  become_method: sudo

- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
  register: build_dir

- name: "Copying merlin-install script to download install merlin"
  copy:
    src: "files/parse_mitre.py"
    dest: "{{ build_dir.path }}/parse_mitre.py"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0755

- name: "Creating MITRE json"
  shell: "/usr/bin/python {{ build_dir.path }}/parse_mitre.py"     
  become: true
  become_method: sudo


# - name: "Creating a symlink"
#   ansible.builtin.shell:
#     cmd: ln -s /opt/havoc/client/Havoc /usr/bin/havoc-client
#   become: true
#   become_method: sudo  

# - name: "Creating a symlink"
#   ansible.builtin.shell:
#     cmd: ln -s /opt/havoc/havoc /usr/bin/havoc-server
#   become: true
#   become_method: sudo