---
- name: Load build-tools catalogs
  ansible.builtin.include_vars:
    dir: "{{ role_path }}/vars"
    extensions:
      - yml
      - yaml

# Comment/Uncomment based on requirments
- import_tasks: needle.yml
- import_tasks: nim.yml
- import_tasks: satellite.yml
- import_tasks: adalanche.yml
- import_tasks: buildbofs.yml
- import_tasks: bloodhound.yml
- import_tasks: windapsearch.yml
- import_tasks: limelighter.yml
- import_tasks: facedancer.yml
  tags: facedancer
#- import_tasks: faceprancer.yml
#  tags: faceprancer
- import_tasks: titanis.yml
- import_tasks: maketools.yml
- name: "Install enabled C2s"
  ansible.builtin.include_tasks:
    file: "{{ item }}.yml"
  loop: "{{ enabled_c2s }}"
- import_tasks: desktop-launchers.yml
#- import_tasks: ghostwriter.yml
#- import_tasks: scarecrow.yml
- import_tasks: finallinks.yml
