---
- name: "Build mythic-cli"
  ansible.builtin.shell:
    cmd: make 
    chdir: /opt/mythic
  become: true
  become_method: sudo

- name: "Verify docker is running"
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  become: true
  become_method: sudo    

- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
  register: build_dir

- name: "Copying mythic-install script to download install mythic"
  copy:
    src: "files/mythic-install.sh"
    dest: "{{ build_dir.path }}/mythic-install.sh"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0755

- name: "Installing Mythic"
  shell: "{{ build_dir.path }}/mythic-install.sh" 
  become: true
  become_method: sudo

- name: Remove temporary build directory
  ansible.builtin.file:
    path: "{{ build_dir.path }}"
    state: absent
  when: build_dir.path is defined 

# - name: "Creating a symlink"
#   ansible.builtin.shell:
#     cmd: ln -s /opt/mythic/mythic-cli /usr/bin/mythic-cli
#   become: true
#   become_method: sudo   

- name: "Stopping Mythic"
  ansible.builtin.shell:
    cmd: /opt/mythic/mythic-cli stop
  become: true
  become_method: sudo 
  ignore_errors: true