---
- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
  register: build_dir

- name: "Copying rust-install script to download install rust"
  copy:
    src: "files/rust-install.sh"
    dest: "{{ build_dir.path }}/rust-install.sh"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0755

- name: "Installing rust"
  shell: "{{ build_dir.path }}/rust-install.sh -y"     

- name: "Installing windows build target"
  shell: "export PATH=$HOME/.cargo/bin:$PATH && rustup target add x86_64-pc-windows-gnu"

- name: "Build rustyneedle"
  shell: "export PATH=$HOME/.cargo/bin:$PATH && cargo build --manifest-path=/opt/rustyneedle/Cargo.toml --target x86_64-pc-windows-gnu --release" 

- name: "Build freeze"
  shell: "export PATH=$HOME/.cargo/bin:$PATH && cargo build --manifest-path=/opt/freeze/Cargo.toml --target x86_64-pc-windows-gnu --release"

- name: "Copying nim-install script to download install nim"
  copy:
    src: "files/nim-install.sh"
    dest: "{{ build_dir.path }}/nim-install.sh"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0755

- name: "Installing Nim"
  shell: "{{ build_dir.path }}/nim-install.sh"    

- name: "Installing packages with Nimble"
  shell: "export PATH=$HOME/.nimble/bin:$PATH && nimble install winim nimcrypto docopt ptr_math strenc -y"



- name: Remove temporary build directory
  ansible.builtin.file:
    path: "{{ build_dir.path }}"
    state: absent
  when: build_dir.path is defined 

