# - name: "Copying nim-install script to download install nim"
#   copy:
#     src: "files/nim-install.sh"
#     dest: "{{ build_dir.path }}/nim-install.sh"
#     owner: "{{ ansible_facts['user_id'] }}"
#     group: "{{ ansible_facts['user_id'] }}"
#     mode: 0755

# - name: "Installing Nim"
#   shell: "{{ build_dir.path }}/nim-install.sh"    

- name: "Installing packages with Nimble"
  shell: "nimble install winim nimcrypto docopt psutil nimprotect supersnappy argparse ptr_math strenc libp2p ws zippy iputils socks5 daemon tiny_sqlite dnsclient -y"