---
- name: "Make Rusthound Linux"
  ansible.builtin.shell:
    cmd: make release
    chdir: /opt/rusthound
  ignore_errors: true  

- name: "Make Rusthound Windows"
  ansible.builtin.shell:
    cmd: make windows
    chdir: /opt/rusthound
  ignore_errors: true  

