---
- name: "Make Rusthound Linux"
  ansible.builtin.shell:
    cmd: "export PATH=$HOME/.cargo/bin:$PATH && make release"
    chdir: /opt/rusthound
  ignore_errors: true  

- name: "Make Rusthound Windows"
  ansible.builtin.shell:
    cmd: "export PATH=$HOME/.cargo/bin:$PATH && make windows"
    chdir: /opt/rusthound
  ignore_errors: true  

