---
# - name: "Copy ZshRC"
#   copy:
#     src: "{{ role_path }}/files/.zshrc"
#     dest: "{{ ansible_env.HOME }}"
#     force: yes

# - name: "Copy Root ZshRC"
#   copy:
#     src: "{{ role_path }}/files/.zshrc"
#     dest: "{{ ansible_env.HOME }}" 
#     force: yes 
#   become: true
#   become_method: sudo 

# - name: "Copy PS profile"
#   copy:
#     src: "{{ role_path }}/files/Microsoft.PowerShell_profile.ps1"
#     dest: "{{ ansible_env.HOME }}/.config/powershell/"
#     force: yes

# - name: "setting go path"
#   shell: 'echo export GOPATH=$HOME/go >> "/home/{{ ansible_user_id }}/.zshrc"'
#   ignore_errors: true  

- name: "setting nimble path"
  shell: 'echo export PATH=/home/kali/.nimble/bin:$PATH >> "/home/{{ ansible_user_id }}/.zshrc"' 
  ignore_errors: true

- name: "setting Rust path"
  shell: 'echo export PATH=$HOME/.cargo/bin:$PATH >> "/home/{{ ansible_user_id }}/.zshrc"' 
  ignore_errors: true

# - name: "Copy Terminal Settings"
#   copy:
#     src: "{{ role_path }}/files/qterminal.ini"
#     dest: "{{ ansible_env.HOME }}/.config/qterminal.org"  
#     force: yes

# - name: "Read current mate terminal profiles"
  # dconf:
  #   key: "/org/mate/terminal/global/profile-list"
  #   state: "read"
  # register: "profile_list"

# - name: "profile_list was not set, setting"
#   set_fact:
#     profile_list: 
#       value: '["default"]'
#   when: profile_list.value is none

# - name: "Adding our profile"
#   set_fact:
#     new_profile_list: "{{ profile_list.value | regex_replace(']$', \", 'video']\") }}"

# - name: "Writing updated profile list"
#   dconf:
#     key: "/org/mate/terminal/global/profile-list"
#     value: "{{ new_profile_list }}"
#   when: "'video' not in profile_list.value"
  
# - name: "Restoring Video Profile from Dump"
#   shell:
#     cmd: "dconf load /org/mate/terminal/profiles/video/ < {{ role_path }}/files/dconf-dump-video"
#   when: "'video' not in profile_list.value"

