---
- name: "Enable rsyslog service"
  service:
    name: rsyslog
    enabled: yes
    state: started
  become: true
  become_method: sudo

- name: "Configure UFW"
  ufw:
    state: enabled
    policy: allow
  become: true
  become_method: sudo

- name: "Log SYN packets in INPUT Chain"
  lineinfile:
    path: /etc/ufw/after.rules
    line: '-A ufw-after-input -p tcp --syn -j LOG --log-prefix "[UFW-SYN-LOG] "'
    insertbefore: "# don't delete the 'COMMIT' line or these rules won't be processed"
  become: true
  become_method: sudo
  
- name: "Restart ufw"
  service:
    name: ufw
    state: restarted
  become: true
  become_method: sudo
        

