---
# tasks file for customize-desktop
- name: "Copy PS profile"
  copy:
    src: "{{ role_path }}/files/"
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/xfce4/xfconf/xfce-perchannel-xml/"
    force: yes