---
- name: "Recursively change ownership and permissions of /opt/"
  ansible.builtin.command:
    cmd: "chown -R {{ ansible_user_id }}:{{ ansible_user_id }} /usr/local/sbin/Ghostwriter/" 
  become: true
  become_method: sudo

- name: "Verify docker is running"
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  become: true
  become_method: sudo

# Dont run on C2 Server eats up port 80/443
- name: "Installing Ghostwriter cli"
  ansible.builtin.shell:
    cmd: "/usr/local/sbin/Ghostwriter/ghostwriter-cli-linux install"
  become: true
  become_method: sudo

- name: "Stopping Ghostwriter" 
  ansible.builtin.shell:
    cmd: "/usr/local/sbin/Ghostwriter/ghostwriter-cli-linux containers stop"
  become: true
  become_method: sudo

