---
- name: "Updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: "Upgrade all packages"
  apt: upgrade=yes force_apt_get=yes
  become: true
  become_method: sudo
  
- name: "Installing Packages"
  package:
    name:
      - kali-linux-everything
      - kali-tools-crypto-stego
      - kali-tools-fuzzing
      - kali-tools-windows-resources
      - kali-linux-large
      - kali-wallpapers-all
      - golang
      - peass
      - bc
      - xplico
      - openssh-server
      - mingw-w64
      - jq
      - pipx
      - ntpdate
      - flameshot
      - exiftool
      - nim
      - veil-evasion
      - evilginx2
      - evilginx2-dbgsym
      - pure-ftpd
      - curl
      - dnsrecon
      - enum4linux
      - feroxbuster
      - nbtscan
      - nikto
      - onesixtyone
      - oscanner
      - redis-tools
      - smbclient
      - smbmap
      - snmp
      - sslscan
      - sipvicious
      - tnscmd10g
      - whatweb
      - wkhtmltopdf
      - docker.io
      - docker-compose
      - podman
      - rsyslog
      - ufw
    state: latest
  become: true
  become_method: sudo
