---
- name: "Updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: "Upgrade all packages"
  apt: upgrade=yes force_apt_get=yes
  become: true
  become_method: sudo
  
- name: "Installing Packages"
  package:
    name:
      - build-essential
      - apt-utils
      - cmake 
      - libfontconfig1 
      - libglu1-mesa-dev 
      - libgtest-dev 
      - libspdlog-dev 
      - libboost-all-dev 
      - libncurses5-dev 
      - libgdbm-dev 
      - libssl-dev 
      - libreadline-dev 
      - libffi-dev 
      - libsqlite3-dev 
      - libbz2-dev 
      - mesa-common-dev 
      - qtbase5-dev 
      - qtchooser 
      - qt5-qmake 
      - qtbase5-dev-tools 
      - libqt5websockets5 
      - libqt5websockets5-dev 
      - qtdeclarative5-dev 
      - golang-go 
      - qtbase5-dev 
      - libqt5websockets5-dev 
      - python3-dev 
      - libboost-all-dev 
      - mingw-w64 
      - nasm
      - kali-linux-everything
      - kali-tools-crypto-stego
      - kali-tools-fuzzing
      - kali-tools-windows-resources
      - kali-linux-large
      - kali-wallpapers-all
      - golang
      - peass
      - bc
      - xplico
      - openssh-server
      - mingw-w64
      - jq
      - pipx
      - ntpdate
      - flameshot
      - exiftool
      - veil-evasion
      - evilginx2
      - evilginx2-dbgsym
      - pure-ftpd
      - curl
      - dnsrecon
      - enum4linux
      - feroxbuster
      - nbtscan
      - nikto
      - onesixtyone
      - oscanner
      - redis-tools
      - smbclient
      - smbmap
      - snmp
      - sslscan
      - sipvicious
      - tnscmd10g
      - whatweb
      - wkhtmltopdf
      - docker.io
      - docker-compose
      - podman
      - apache2
      - postfix
      - nginx
      - whois
      - rsyslog
      - ufw
      - rlwrap
      - openssl
      - osslsigncode
    state: latest
  become: true
  become_method: sudo

- name: "Starting and Enabling Services"
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
     - ssh
     - rsyslog
     - ufw
  become: true
  become_method: sudo

- name: pipx check
  command: pipx ensurepath
  become: true
  become_method: sudo