---
- name: "install Kerbrute"
  shell: go install github.com/ropnop/kerbrute@master

- name: "install go color"
  shell: go install github.com/ropnop/color@latest

- name: "install go zip"
  shell: go install github.com/yeka/zip@master

- name: "install go version info"
  shell: go install github.com/josephspurrier/goversioninfo@master

- name: "install go pe debug"
  shell: go install github.com/Binject/debug/pe@master 

- name: "install go rawreader"
  shell: go install github.com/awgh/rawreader@master 

- name: "install go satellite"
  shell: go install github.com/t94j0/satellite@master

