---
- name: "Creating Redirector directory"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Desktop/redirector"
    state: directory
    mode: '0755'

- name: "Adding files to new directory"
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/Desktop/redirector/"
  with_fileglob:
    - "{{ role_path }}/files/"  

- name: "Enabling Apache Mods"
  command: "a2enmod {{ item }}"
  loop:
    - proxy
    - proxy_http
    - rewrite
    - headers
    - ssl
    - cache
  become: true
  become_method: sudo

