---
- name: "Creating Redirector directory"
  ansible.builtin.file:
    path: "/opt/redirector"
    state: directory
    mode: '0755'

- name: "Adding files to new directory"
  copy:
    src: "{{ item }}"
    dest: "/opt/redirector/"
  with_fileglob:
    - "{{ role_path }}/files/*"  

- name: "Adding ca directory"
  copy:
    src: "{{ role_path }}/files/ca"
    dest: "/opt/redirector/ca/"
    remote_src: true
    
- name: "Adding phish directory"
  copy:
    src: "{{ role_path }}/files/phish"
    dest: "/opt/redirector/phish/"
    remote_src: true 

- name: "Enabling Apache Mods"
  command: "a2enmod {{ item }}"
  loop:
    - proxy
    - proxy_http
    - rewrite
    - headers
    - ssl
    - cache
  become: true
  become_method: sudo

